// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

package main

import "fmt"

func main() {

	terms := []int{1, 2}
	last, sum := 0, 0

	for {
		last = terms[len(terms)-1] + terms[len(terms)-2]
		if last < 4000000 {
			terms = append(terms, last)
		} else {
			break
		}
	}

	for _, value := range terms {
		if value%2 == 0 {
			sum += value
		}
	}

	fmt.Println("Sum is", sum)

}
