// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

package main

import "fmt"

func main() {
	terms, sum := []int{1, 1}, 0
	for last := 0; last < 4000000; last = terms[len(terms)-1] + terms[len(terms)-2] {
		if last%2 == 0 {
			sum += last
		}
		terms = append(terms, last)
	}
	fmt.Println("Sum is", sum)
}
