// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

package main

func main() {
	seq, sum := []int{1, 1}, 0
	for i := 0; i < 4000000; i = seq[len(seq)-1] + seq[len(seq)-2] {
		if i%2 == 0 {
			sum += i
		}
		seq = append(seq, i)
	}
	println("Sum is", sum)
}
